In [1]:
import torch
import numpy

In [2]:
a = torch.tensor([0])
b = torch.tensor([0, 1])
c = torch.tensor([[0], [1]])
d = torch.t(c)
d

tensor([[0, 1]])

In [3]:
e = numpy.array([0, 1])
f = torch.from_numpy(e)
print(f*100000000000)

tensor([         0, 1215752192], dtype=torch.int32)


In [4]:
g = torch.ones_like(f)
h = torch.rand_like(f, dtype=torch.float)
h

tensor([0.4322, 0.2411])

In [5]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}, {tensor.dtype}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4]), torch.float32
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [6]:
if torch.cuda.is_available():
    tensor = tensor.to("cuda")

print(tensor.device)

cuda:0


In [7]:
tensor = torch.ones([4, 4, 4])
tensor[0, ...] = 0
# tensor = torch.cat([tensor, tensor, tensor], dim = 2)
print(tensor)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])


In [8]:
tensor1 = torch.tensor([1, 2, 3, 4])
tensor2 = torch.tensor([[1, 2, 3, 4], [2, 3, 4, 5], [1, 2, 3, 4], [2, 3, 4, 5]])
print(torch.matmul(tensor1, tensor2))
tensor = torch.ones([4, 4])
y3 = torch.rand_like(tensor.float())
y4 = torch.ones_like(y3)
print(torch.matmul(y3, y3.T, out=y4))
y5 = y3 @ y3.T
print(y5 == y4)

tensor([16, 26, 36, 46])
tensor([[0.8354, 0.7218, 1.0167, 0.4785],
        [0.7218, 0.7478, 0.7279, 0.4225],
        [1.0167, 0.7279, 1.5779, 0.6378],
        [0.4785, 0.4225, 0.6378, 0.3271]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [9]:
tensor = torch.tensor([[1, 2, 3, 5], [2, 3, 4, 5]])
agg = tensor.sum().item()
print(f"{tensor}")
n = tensor.numpy()
print(f"{n}")
tensor = tensor.add_(5)
print(f"{tensor}")
print(f"{n}")

tensor([[1, 2, 3, 5],
        [2, 3, 4, 5]])
[[1 2 3 5]
 [2 3 4 5]]
tensor([[ 6,  7,  8, 10],
        [ 7,  8,  9, 10]])
[[ 6  7  8 10]
 [ 7  8  9 10]]


In [11]:
a = tensor.float()
print(a)

tensor([[ 6.,  7.,  8., 10.],
        [ 7.,  8.,  9., 10.]])


In [19]:
three = torch.rand([3, 4, 5])*10
print(three)
three[2]

tensor([[[5.3050, 4.3900, 5.7852, 6.9054, 2.5551],
         [0.5011, 3.5320, 4.1759, 9.8309, 6.2962],
         [1.4065, 4.0444, 4.3399, 7.5416, 6.3432],
         [7.8352, 8.7920, 3.1381, 6.3337, 6.0502]],

        [[2.5306, 9.5310, 1.8379, 2.8526, 6.4841],
         [9.6375, 9.4926, 7.5960, 5.7355, 9.9224],
         [1.3813, 8.3828, 5.7183, 5.6497, 1.1191],
         [8.3038, 0.8610, 9.3517, 9.2442, 4.6675]],

        [[5.3910, 7.3777, 6.6001, 1.7749, 6.8757],
         [6.7161, 3.5631, 6.7071, 6.2344, 3.9178],
         [3.1284, 6.0330, 8.4625, 6.3287, 4.2152],
         [9.2663, 5.0223, 9.9890, 5.7620, 3.8498]]])


tensor([[5.3910, 7.3777, 6.6001, 1.7749, 6.8757],
        [6.7161, 3.5631, 6.7071, 6.2344, 3.9178],
        [3.1284, 6.0330, 8.4625, 6.3287, 4.2152],
        [9.2663, 5.0223, 9.9890, 5.7620, 3.8498]])