In [8]:
import numpy as np

# 都是1维向量的时候

In [3]:
a = np.array([1, 2, 3])
b = np.array([2, 4, 6])
print(np.dot(a, b))         # 内积
print(np.outer(a, b))       # 叉乘
print(a * b)                # 对应元素相乘
print(a @ b)                # 内积

28
[[ 2  4  6]
 [ 4  8 12]
 [ 6 12 18]]
[ 2  8 18]
28


# 1维和2维向量的时候，.dot

In [27]:
in1 = np.array([2, 3, 3, 4])
in2 = np.array([[[2, 3, 4, 5], [1, 1, 2, 2], [1, 1, 2, 2]],[[1, 3, 4, 4], [2, 2, 3, 3], [2, 2, 3, 3]]])
in3 = in2[:,:,0] * 2
in4 = in2[:,:,1] * 3
in5 = in2[:,:,2] * 3
in6 = in2[:,:,3] * 4
print(in3)
print(in4)
print(in3 + in4 + in5 + in6)
print(np.dot(in2, in1))

[[4 2 2]
 [2 4 4]]
[[9 3 3]
 [9 6 6]]
[[45 19 19]
 [39 31 31]]
[[45 19 19]
 [39 31 31]]


# 2维和1维向量乘

In [44]:
ma1 = [[1,3,5],[2,4,6]]
ma2 = [1,2]                 # 计算是有顺序的，永远按第一个元素展开
print(np.dot(ma2, ma1))
print(ma1[0])
print(ma1[1])

# 反过来
ma3 = [[1,3,5],[2,4,6]]
ma4 = [1,2,3]                 # 计算是有顺序的，永远按第一个元素展开
print(np.dot(ma3, ma4))



ValueError: shapes (2,3) and (2,) not aligned: 3 (dim 1) != 2 (dim 0)

# Numpy 的维度

In [31]:
np1 = np.array([3,2,1])
print(np1.shape)
np2 = np.array([[3],[2],[1]])
print(np2.shape)
np3 = np.array([[[2, 3, 4, 5], [1, 1, 2, 2], [1, 1, 2, 2]],[[1, 3, 4, 4], [2, 2, 3, 3], [2, 2, 3, 3]]])
print(np3.shape)

(3,)
(3, 1)
(2, 3, 4)
